---
version: '3.7'
services:
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8083"
    depends_on: 
      - db
    container_name: java-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=${{ secret.POSTGRES_USER }}
      - SPRING_DATASOURCE_PASSWORD=${{ secret.POSTGRES_PASSWORD }}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - appnetwork
  db:
    image: 'postgres:14.2-alpine'
    container_name: postgres
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DATABASE=${{ secret.POSTGRES_DATABASE }}
      - POSTGRES_USER=${{ secret.POSTGRES_USER }}
      - POSTGRES_PASSWORD=${{ secret.POSTGRES_PASSWORD }}
    volumes:
      - container-volume:/var/lib/postgres/data
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - appnetwork

volumes:
  container-volume:

networks:
  appnetwork:
    driver: bridge
